# Generated by Django 4.1.7 on 2023-03-22 20:17

from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_user_is_verified_otp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="date_updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="phone",
            field=models.CharField(
                max_length=14, validators=[utils.validators.validate_phone_number]
            ),
        ),
    ]
