# Generated by Django 4.1.7 on 2023-03-24 14:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_profile_date_updated_alter_profile_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersettings",
            name="app_updates",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="usersettings",
            name="biometric",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="usersettings",
            name="cashback",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="usersettings",
            name="face_id",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="usersettings",
            name="language",
            field=models.CharField(default="english", max_length=50),
        ),
        migrations.AddField(
            model_name="usersettings",
            name="notification",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="usersettings",
            name="payments",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="usersettings",
            name="sound",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="usersettings",
            name="special_offers",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="usersettings",
            name="vibrate",
            field=models.BooleanField(default=True),
        ),
    ]
