# Generated by Django 4.1.7 on 2023-03-23 14:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="property",
            options={"verbose_name_plural": "Properties"},
        ),
        migrations.AlterField(
            model_name="product",
            name="property",
            field=models.ManyToManyField(to="shop.property"),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="property",
            field=models.ManyToManyField(to="shop.property"),
        ),
        migrations.AlterField(
            model_name="property",
            name="color",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="property",
            name="size",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
