# Generated by Django 4.1.7 on 2023-03-24 16:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0003_cart_order_trackorder_orderitem_billingaddress_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Color",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("color", models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Size",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("size", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "Properties",
            },
        ),
        migrations.RemoveField(
            model_name="product",
            name="property",
        ),
        migrations.RemoveField(
            model_name="productimage",
            name="property",
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("complete", "Complete"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
        migrations.DeleteModel(
            name="Property",
        ),
        migrations.AddField(
            model_name="product",
            name="colors",
            field=models.ManyToManyField(to="shop.color"),
        ),
        migrations.AddField(
            model_name="product",
            name="sizes",
            field=models.ManyToManyField(to="shop.size"),
        ),
        migrations.AddField(
            model_name="productimage",
            name="colors",
            field=models.ManyToManyField(to="shop.color"),
        ),
        migrations.AddField(
            model_name="productimage",
            name="sizes",
            field=models.ManyToManyField(to="shop.size"),
        ),
    ]
