# Generated by Django 4.1.7 on 2023-03-24 20:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0004_color_size_remove_product_property_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="size",
            options={},
        ),
        migrations.AlterField(
            model_name="product",
            name="colors",
            field=models.ManyToManyField(blank=True, to="shop.color"),
        ),
        migrations.AlterField(
            model_name="product",
            name="sizes",
            field=models.ManyToManyField(blank=True, to="shop.size"),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="colors",
            field=models.ManyToManyField(blank=True, to="shop.color"),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="sizes",
            field=models.ManyToManyField(blank=True, to="shop.size"),
        ),
    ]
