# Generated by Django 4.1.7 on 2023-03-29 20:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0005_alter_size_options_alter_product_colors_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_digital",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
