# Generated by Django 4.1.7 on 2023-04-02 22:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_rename_color_color_color_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
    ]
