# Generated by Django 4.1.7 on 2023-04-02 22:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_productimage_unit_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='unit_price',
        ),
        migrations.AddField(
            model_name='productsizecolorinventory',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
    ]
