# Generated by Django 4.1.7 on 2023-04-03 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_alter_productcolorinventory_product_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductColorInventory',
            new_name='ColorInventory',
        ),
        migrations.RenameModel(
            old_name='ProductSizeInventory',
            new_name='SizeInventory',
        ),
    ]
