# Generated by Django 4.1.7 on 2023-04-03 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_rename_productcolorinventory_colorinventory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorinventory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_inventory', to='shop.product'),
        ),
        migrations.AlterField(
            model_name='sizeinventory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size_inventory', to='shop.product'),
        ),
    ]
