# Generated by Django 4.1.7 on 2023-04-03 12:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0014_alter_colorinventory_product_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="colorinventory",
            options={"verbose_name_plural": "Product Color & Inventories"},
        ),
        migrations.RemoveField(
            model_name="color",
            name="color_code",
        ),
        migrations.AddField(
            model_name="color",
            name="hex_code",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="color",
            name="name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
