# Generated by Django 4.1.7 on 2023-04-03 13:20

from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("shop", "0015_alter_colorinventory_options_remove_color_color_code_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("OFFER", "OFFER"),
                            ("FEED", "FEED"),
                            ("ACTIVITY", "ACTIVITY"),
                        ],
                        max_length=200,
                    ),
                ),
                ("title", models.CharField(max_length=200, null=True)),
                ("desc", models.CharField(max_length=200, null=True)),
                ("general", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("users", models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
