# Generated by Django 4.1.7 on 2023-04-03 16:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0016_notification"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="cartitem",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="product",
            name="colors",
        ),
        migrations.RemoveField(
            model_name="product",
            name="sizes",
        ),
        migrations.AlterField(
            model_name="product",
            name="unit_price",
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
