# Generated by Django 4.1.7 on 2023-04-03 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sizeinventory',
            name='size',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
