# Generated by Django 4.1.7 on 2023-04-03 20:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0017_alter_cartitem_unique_together_remove_product_colors_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productimage",
            name="colors",
        ),
        migrations.RemoveField(
            model_name="productimage",
            name="sizes",
        ),
        migrations.AlterField(
            model_name="colorinventory",
            name="quantity",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name="colorinventory",
            name="unit_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AlterField(
            model_name="sizeinventory",
            name="quantity",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name="sizeinventory",
            name="size",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="sizeinventory",
            name="unit_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
    ]
