# Generated by Django 4.1.7 on 2023-04-03 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0018_remove_productimage_colors_remove_productimage_sizes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="size",
            name="size",
            field=models.CharField(default="M", max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="sizeinventory",
            name="size",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_size",
                to="shop.size",
            ),
        ),
    ]
