# Generated by Django 4.1.7 on 2023-04-03 21:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0019_alter_size_size_alter_sizeinventory_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="color",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cartitem",
            name="size",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
    ]
