# Generated by Django 4.1.7 on 2023-04-03 21:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0020_cartitem_color_cartitem_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="color",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="size",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="color",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="size",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
