# Generated by Django 4.1.7 on 2023-04-03 22:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0021_orderitem_color_orderitem_size_alter_cartitem_color_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="colorinventory",
            old_name="unit_price",
            new_name="extra_price",
        ),
        migrations.RenameField(
            model_name="sizeinventory",
            old_name="unit_price",
            new_name="extra_price",
        ),
    ]
