# Generated by Django 4.1.7 on 2023-04-06 17:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0022_rename_unit_price_colorinventory_extra_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="size",
            name="size",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
