# Generated by Django 4.1.7 on 2023-04-06 17:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0023_alter_size_size"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="color",
            unique_together={("name", "hex_code")},
        ),
    ]
