# Generated by Django 4.1.7 on 2023-04-06 17:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0024_alter_color_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="color",
            name="name",
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
