# Generated by Django 4.2 on 2023-04-10 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0025_alter_color_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="item",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="shop.cartitem",
            ),
            preserve_default=False,
        ),
    ]
