# Generated by Django 4.2 on 2023-04-07 20:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0025_alter_color_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="hex_code",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
