# Generated by Django 4.2 on 2023-04-07 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0026_cartitem_hex_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="ColorSizeInventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(blank=True, default=0)),
                (
                    "extra_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "color",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_color",
                        to="shop.color",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="color_inventory",
                        to="shop.product",
                    ),
                ),
                (
                    "size",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_size",
                        to="shop.size",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Product Color & Size Inventories",
            },
        ),
        migrations.RemoveField(
            model_name="sizeinventory",
            name="product",
        ),
        migrations.RemoveField(
            model_name="sizeinventory",
            name="size",
        ),
        migrations.DeleteModel(
            name="ColorInventory",
        ),
        migrations.DeleteModel(
            name="SizeInventory",
        ),
    ]
