# Generated by Django 4.2 on 2023-04-07 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0027_colorsizeinventory_remove_sizeinventory_product_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="colorsizeinventory",
            name="color",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_color",
                to="shop.color",
            ),
        ),
        migrations.AlterField(
            model_name="colorsizeinventory",
            name="size",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_size",
                to="shop.size",
            ),
        ),
    ]
