# Generated by Django 4.2 on 2023-04-10 10:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0028_order_color_order_product_order_quantity_order_size_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="unit_price",
            new_name="price",
        ),
    ]
