# Generated by Django 4.2 on 2023-04-08 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0028_alter_colorsizeinventory_color_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="colorsizeinventory",
            options={
                "verbose_name": "Color & Size Inventory",
                "verbose_name_plural": "Product Color & Size Inventories",
            },
        ),
        migrations.AlterField(
            model_name="colorsizeinventory",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="color_size_inventory",
                to="shop.product",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="colorsizeinventory",
            unique_together={("color", "size")},
        ),
    ]
