# Generated by Django 4.2 on 2023-04-08 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0029_alter_colorsizeinventory_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="hex_code",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cart_items",
                to="shop.product",
            ),
        ),
    ]
