# Generated by Django 4.2 on 2023-04-12 15:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0029_rename_unit_price_order_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="hex_code",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="hex_code",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
